# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://radimmusalek.com # http://RadimMusalek.github.io/
baseurl: /radimmusalek.github.io/ # /CV/
title: Radim Mušálek
author: Radim Mušálek
description: Personal blog and resume
avatar: profile.png
email: musalek.radim (at) gmail.com
github: RadimMusalek # username
# twitter: radim_musalek
linkedin: radim-mušálek-1142b824
# stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
# disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]

theme: jekyll-theme-architect
